CI: Fail pycoverage job is python coverage is below goal

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -245,10 +245,21 @@ apidoc:
 pycoverage:
   stage: coverage
   image: debian:12
+  variables:
+    GOAL: "92"
   script:
     - apt update
     - apt install -y python3 python3-pip python3-venv
-    - make pycoverage
+    - make pycoverage | tee pycoverage.log
+    - LASTFIELD=$(grep 'TOTAL' coverage.log | awk '{print $NF}')
+    - PERCENTAGE=${LASTFIELD%\%}
+    - |
+      if [ "$(echo "$PERCENTAGE < $GOAL" | bc)" -eq 1 ]; then
+        echo "ERROR: Python coverage $PERCENTAGE is below goal $GOAL"
+        exit 1
+      else
+        echo "SUCCESS: Python coverage $PERCENTAGE equal or better than goal $GOAL"
+      fi
   coverage: /TOTAL.*\s+(\d+\%)/
   artifacts:
     when: always
