CI: fail apidoc job if number of undocumented bigger than goal
- This commit also ensures that 'bc' is installed in the jobs that need
  it

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -14,7 +14,7 @@ count_todos_in_code:
     GOAL: "60"
   script:
     - apt update
-    - apt install -y python3 python3-pip python3-venv
+    - apt install -y python3 python3-pip python3-venv bc
     - make todo | tee todo.log
     - TODOS=$(grep -oP 'TODOs=\K[\d]+' todo.log)
     - |
@@ -227,10 +227,20 @@ full_dashboard:
 apidoc:
   stage: doc
   image: debian:12
+  variables:
+    GOAL: 98
   script:
     - apt update
-    - apt install -y python3 python3-pip python3-venv
-    - make docs
+    - apt install -y python3 python3-pip python3-venv bc
+    - make docs 2>&1 | tee docs.log
+    - UNDOCUMENTED=$(grep -oP 'Total undocumented members= \K[\d]+' docs.log)
+    - |
+      if [ "$(echo "$UNDOCUMENTED > $GOAL" | bc)" -eq 1 ]; then
+        echo "ERROR: Number of undocumented $UNDOCUMENTED is over goal $GOAL"
+        exit 1
+      else
+        echo "SUCCESS: Number of undocumented $UNDOCUMENTED is equal or lower than goal $GOAL"
+      fi
   artifacts:
     when: always
     paths:
@@ -260,7 +270,7 @@ pycoverage:
     GOAL: "92"
   script:
     - apt update
-    - apt install -y python3 python3-pip python3-venv
+    - apt install -y python3 python3-pip python3-venv bc
     - make pycoverage | tee pycoverage.log
     - LASTFIELD=$(grep 'TOTAL' pycoverage.log | awk '{print $NF}')
     - PERCENTAGE=${LASTFIELD%\%}
