CI: fail count_todos_in_code if number of todos is above goal

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -10,12 +10,23 @@ stages:
 count_todos_in_code:
   stage: lint_and_test
   image: debian:12
+  variables:
+    GOAL: "60"
   script:
     - apt update
     - apt install -y python3 python3-pip python3-venv
-    - make todo
+    - make todo | tee todo.log
+    - TODOS=$(grep -oP 'TODOs=\K[\d]+' todo.log)
+    - |
+      if [ "$(echo "$TODOS > $GOAL" | bc)" -eq 1 ]; then
+        echo "ERROR: Number of TODOs $TODOS is over goal $GOAL"
+        exit 1
+      else
+        echo "SUCCESS: Number of TODOs $TODOS is equal or lower than goal $GOAL"
+      fi
   coverage: /Count=([\d]+)/
   artifacts:
+    when: always
     paths:
       - badges/todo.svg
 
